set nocompatible
filetype off
syntax on

filetype plugin indent on
filetype plugin on

set encoding=utf-8

set tabstop=2
set softtabstop=0
set expandtab
set shiftwidth=2
set smarttab

set noerrorbells 
set novisualbell
set t_vb=
set belloff=all
set visualbell t_vb=
autocmd! GUIEnter * set vb t_vb=

autocmd FileType ruby setlocal shiftwidth=2 tabstop=2
autocmd FileType lua setlocal shiftwidth=2 tabstop=2
autocmd FileType json setlocal shiftwidth=2 tabstop=2
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2
autocmd FileType html setlocal shiftwidth=2 tabstop=2

set textwidth=120
set ruler
set number

function! FZF() abort
    let l:tempname = tempname()
    " fzf | awk '{ print $1":1:0" }' > file
    execute 'silent !fzf -i --multi ' . '| awk ''{ print $1":1:0" }'' > ' . fnameescape(l:tempname)
    try
        execute 'cfile ' . l:tempname
        redraw!
    finally
        call delete(l:tempname)
    endtry
endfunction

" :Files
command! -nargs=* Files call FZF()

" \ff
nnoremap <leader>ff :Files<cr>
