set nocompatible
filetype off
syntax on

filetype plugin indent on
filetype plugin on

set encoding=utf-8

set tabstop=4
set softtabstop=0
set expandtab
set shiftwidth=4
set smarttab

set noerrorbells 
set novisualbell
set t_vb=
set belloff=all
set visualbell t_vb=
autocmd! GUIEnter * set vb t_vb=

autocmd FileType ruby setlocal shiftwidth=2 tabstop=2

set ruler
set number

if has("linux")
    set rtp+=~/.vim/fzf
elseif has("mac")
    set rtp+=/usr/local/opt/fzf
endif

set rtp+=~/.vim/plugin

if has("gui_running")
    if has("gui_macvim")
        set guifont=Monaco:h12
        macmenu &File.Print key=<nop>
    endif
    colorscheme slate
else
    colorscheme slate
endif

nnoremap <silent> <D-p> :FZF<cr>
inoremap <silent> <D-p> <Esc>:FZF<cr>
nnoremap <silent> <C-p> :FZF<cr>
inoremap <silent> <C-p> <Esc>:FZF<cr>

nnoremap <silent> <Leader>rg :Rg <C-R><C-W><CR>

nnoremap <leader>nn :NERDTreeFocus<CR>
" nnoremap <C-n> :NERDTree<CR>
" nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <leader>nf :NERDTreeFind<CR>

" If another buffer tries to replace NERDTree, put it in the other window, and bring back NERDTree.
autocmd BufEnter * if bufname('#') =~ 'NERD_tree_\d\+' && bufname('%') !~ 'NERD_tree_\d\+' && winnr('$') > 1 |
    \ let buf=bufnr() | buffer# | execute "normal! \<C-W>w" | execute 'buffer'.buf | endif
