set nocompatible
filetype off
syntax on

filetype plugin indent on
filetype plugin on

set encoding=utf-8

set tabstop=4
set softtabstop=0
set expandtab
set shiftwidth=4
set smarttab

autocmd FileType ruby setlocal shiftwidth=2 tabstop=2

set ruler
set number

if has("linux")
    set rtp+=~/.vim/fzf
elseif has("mac")
    set rtp+=/usr/local/opt/fzf
endif

set rtp+=~/.vim/plugin

if has("gui_running")
    if has("gui_macvim")
        set guifont=Monaco:h12
        macmenu &File.Print key=<nop>
        aunmenu File.Print
    endif
    colorscheme slate
else
    colorscheme slate
endif

nnoremap <silent> <D-p> :FZF<cr>
inoremap <silent> <D-p> <Esc>:FZF<cr>
nnoremap <silent> <C-p> :FZF<cr>
inoremap <silent> <C-p> <Esc>:FZF<cr>

nnoremap <silent> <Leader>rg :Rg <C-R><C-W><CR>
