#!/usr/bin/env zsh
# vim: set syntax=zsh:
    
notebook_dir="$HOME/notebooks/jupyter"
mkdir -p $notebook_dir

docker run --rm \
    -p 10000:8888 \
    -e JUPYTER_ENABLE_LAB=yes \
    -v "$notebook_dir":/home/jovyan/work \
    --name jupyterlab \
    jupyter/all-spark-notebook:r-4.1.1 2>&1 | \
sed -u "s/http:\/\/127.0.0.1:8888\(\/.*\)/`printf "\033[1;38;2;255;255;0m"`http:\/\/127.0.0.1:10000\1`print "\033[0m"`/"
