#!/usr/bin/env zsh
# vim: set syntax=zsh:
    
notebook_dir="$HOME/notebooks/iruby"
mkdir -p $notebook_dir
port=10002

docker run --rm \
    -p $port:8888 \
    -e JUPYTER_ENABLE_LAB=yes \
    -v "$notebook_dir":/home/jovyan/work \
    --name iruby \
    d1d813f56a7e 2>&1 | \
sed -u "s/http:\/\/127.0.0.1:8888\(\/.*\)/`printf "\033[1;38;2;255;255;0m"`http:\/\/127.0.0.1:$port\1`print "\033[0m"`/"
