#!/usr/bin/env zsh
# vim: set syntax=zsh:
    
notebook_dir="$HOME/notebooks/zeppelin"
mkdir -p $notebook_dir
    
local port=10001
printf "server: \033[1;38;2;255;255;0mhttp://127.0.0.1:$port\033[0m\n"

docker run --rm \
    -u $(id -u) \
    -p $port:8080 \
    -v $notebook_dir:/notebook \
    -e ZEPPELIN_NOTEBOOK_DIR='/notebook' \
   --name zeppelin \
   apache/zeppelin:0.10.0
